# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=250)),
                ('brief', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('note_logo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
