# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='brief',
            field=models.TextField(max_length=100),
        ),
    ]
