# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20170725_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='is_private',
            new_name='private',
        ),
    ]
