# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20170725_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='note',
            name='brief',
            field=models.CharField(max_length=100),
        ),
    ]
