# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20170725_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_logo',
            field=models.FileField(blank=True, default='/media/no-image-slide.png', null=True, upload_to=''),
        ),
    ]
