# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20170726_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_logo',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
